version: "3"

services:
  db:
    image: postgres:10.4-alpine
    volumes:
          - ./postgre/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "testuser"
      POSTGRES_PASSWORD: "testpass"
      POSTGRES_DB: "todo"
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    links:
      - db
    ports:
      - 8080:8080
